# .github/workflows/semantic.release.yaml
name: Release

on:
  push:
    branches:
      - master

jobs:
  build-releses-matrix:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin, openbsd ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: openbsd
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - name: go build action
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.17
          binary_name: mailrelay-${{ matrix.goos }}-${{ matrix.goarch }}
  semantic-release:
    name: semantic release
    runs-on: ubuntu-latest
    needs: release-linux-amd64
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}